//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpJulioSolorzano.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_PRICE
    {
        public long ID { get; set; }
        public long PRODUCT_ID { get; set; }
        public long LIST_ID { get; set; }
        public System.DateTime DATE_INIT { get; set; }
        public System.DateTime DATE_END { get; set; }
        public decimal VALUE { get; set; }
        public bool STATE { get; set; }
    
        public virtual LIST LIST { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
