//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpJulioSolorzano.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TEST_DEVEntities : DbContext
    {
        public TEST_DEVEntities()
            : base("name=TEST_DEVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LIST> LIST { get; set; }
        public virtual DbSet<PRODUCT> PRODUCT { get; set; }
        public virtual DbSet<PRODUCT_TAX> PRODUCT_TAX { get; set; }
        public virtual DbSet<PRODUCTO_PRICE> PRODUCTO_PRICE { get; set; }
        public virtual DbSet<TAX> TAX { get; set; }
        public virtual DbSet<vProductoDetalleImpuestos> vProductoDetalleImpuestos { get; set; }
    }
}
