//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpJulioSolorzano.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProductoDetalleImpuestos
    {
        public long PRODUCT_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string PRICE_LIST_NAME { get; set; }
        public decimal PRODUCT_PRICE { get; set; }
        public decimal PRODUCT_TAX { get; set; }
        public Nullable<decimal> PERCENTAGE { get; set; }
        public decimal MONEY { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
    }
}
